from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class Severity(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class Alert(BaseModel):
    """
    Generated by the detection engine when a rule matches an incoming event.

    Phase 1: schema only — no storage yet. Storage and persistence land in Phase 5.
    """

    id: str = Field(..., description="Unique alert ID (UUID)")
    rule_id: str = Field(..., description="ID of the rule that triggered this alert")
    rule_name: str
    severity: Severity
    host_id: str
    event_type: str
    action: str
    ts: datetime = Field(..., description="Timestamp of the triggering event")
    detected_at: datetime = Field(..., description="Timestamp when the alert was generated")
    detail: dict[str, Any] = Field(default_factory=dict, description="Rule-specific context")
